### ISSUE TITLE
feat: #4 메인 페이지 퍼블리싱

### ISSUE THREAD

**Issue by ijaesin** [CodeMentor-CodingSite/CodeMentor-Front#4]
## 기능 정의

- 메인 페이지를 퍼블리싱 합니다.

<br>

## 작업 상세 내용

- [x] 헤더 바
- [x] 푸터 바
- [x] 스터디 플랜
- [ ] 문제 카테고리 바
- [ ] 문제 리스트
- [ ] 문제 리스트 페이지네이션
- [x] 다크 모드 토글 버튼

<br>

## 참고 자료 (선택사항)

- 메인 페이지 피그마 디자인
<img width="627" alt="image" src="https://github.com/CodeMentor-CodingSite/CodeMentor-Front/assets/80256934/834e9856-6aef-4493-a4b5-5d18fae6004f">

**Comment by EUNSUN23** [comment]
재신님, RootLayout에 lightmode background 색상 white로 적용하신 것 재신님이 작업하신 컴포넌트 내에 작성 해주실 수 있을까요? 로그인, 회원가입 페이지 등 배경색상 다른 페이지도 있어서요~. 

```js
import type { Metadata } from 'next';
import Providers from './providers';
import '@/styles/globals.css';
import { inter } from '@/public/fonts/fonts';
import Header from '@/components/common/Header';
import Footer from '@/components/common/Footer';

export const metadata: Metadata = {
  title: 'Code Mentor',
  description: 'Site to practice coding test',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} bg-white dark:bg-backgroundDark h-full min-h-screen w-full dark:text-white text-black`}
      >
        <Providers>
          <Header />
          <main className="h-full mx-auto my-16 w-desktop">{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}

```

**Comment by ijaesin** [comment]
> 재신님, RootLayout에 lightmode background 색상 white로 적용하신 것 재신님이 작업하신 컴포넌트 내에 작성 해주실 수 있을까요? 로그인, 회원가입 페이지 등 배경색상 다른 페이지도 있어서요~.
> 
> ```js
> import type { Metadata } from 'next';
> import Providers from './providers';
> import '@/styles/globals.css';
> import { inter } from '@/public/fonts/fonts';
> import Header from '@/components/common/Header';
> import Footer from '@/components/common/Footer';
> 
> export const metadata: Metadata = {
>   title: 'Code Mentor',
>   description: 'Site to practice coding test',
> };
> 
> export default function RootLayout({
>   children,
> }: {
>   children: React.ReactNode;
> }) {
>   return (
>     <html lang="en">
>       <body
>         className={`${inter.variable} bg-white dark:bg-backgroundDark h-full min-h-screen w-full dark:text-white text-black`}
>       >
>         <Providers>
>           <Header />
>           <main className="h-full mx-auto my-16 w-desktop">{children}</main>
>           <Footer />
>         </Providers>
>       </body>
>     </html>
>   );
> }
> ```

그럼 편리하게 라이트모드 배경색상을 모두 'F7F8FA'나 'FFFFFF' 중 하나로 통일해서 하는건 어떠신가요 ?

**Comment by EUNSUN23** [comment]
> > 재신님, RootLayout에 lightmode background 색상 white로 적용하신 것 재신님이 작업하신 컴포넌트 내에 작성 해주실 수 있을까요? 로그인, 회원가입 페이지 등 배경색상 다른 페이지도 있어서요~.
> > ```js
> > import type { Metadata } from 'next';
> > import Providers from './providers';
> > import '@/styles/globals.css';
> > import { inter } from '@/public/fonts/fonts';
> > import Header from '@/components/common/Header';
> > import Footer from '@/components/common/Footer';
> > 
> > export const metadata: Metadata = {
> >   title: 'Code Mentor',
> >   description: 'Site to practice coding test',
> > };
> > 
> > export default function RootLayout({
> >   children,
> > }: {
> >   children: React.ReactNode;
> > }) {
> >   return (
> >     <html lang="en">
> >       <body
> >         className={`${inter.variable} bg-white dark:bg-backgroundDark h-full min-h-screen w-full dark:text-white text-black`}
> >       >
> >         <Providers>
> >           <Header />
> >           <main className="h-full mx-auto my-16 w-desktop">{children}</main>
> >           <Footer />
> >         </Providers>
> >       </body>
> >     </html>
> >   );
> > }
> > ```
> 
> 그럼 편리하게 라이트모드 배경색상을 모두 'F7F8FA'나 'FFFFFF' 중 하나로 통일해서 하는건 어떠신가요 ?

네 그러려구요 fff로 통일하겠습니다.
